### ISSUE TITLE
Api Not Found

### ISSUE THREAD

**Issue by Speedxinfotech** [PhonePe/PhonePePayment#3]
failure(PhonePePayment.TransactionFailureError.networkFailure(code: "400", message: "Bad Request - Api Mapping Not Found"))

while initiate the phonepe Sdk than i got this error.
i flow the documentation.
Request Endpoint: https://api-preprod.phonepe.com/apis/pg-sandbox/pg/v1/pay
Request Checksum: xxxx
Request Headers: [:]
Request App Schema: iOSIntentIntegration
PhonePePayment[debug]: Event name: SDK_API_CALLED - data: ["sdkApiName": "SDK_PG_V1_STARTED"]
PhonePePayment[debug]: Event name: B2B_PG_START_CALLED - data: ["merchantId": "", "transactionId": "PP_XEV1EIL4EU29XIAYJLJG"]
PhonePePayment[debug]: Event name: B2B_PG_TRANSACTION_REQUEST_CREATED - data: ["merchantId": "", "transactionId": "PP_XEV1EIL4EU29XIAYJLJG"]
PhonePePayment[debug]: Event name: B2B_PG_API_CALL_STARTED - data: ["merchantId": "", "transactionId": "PP_XEV1EIL4EU29XIAYJLJG"]
[HTTPClient] [INFO]: [<NSMutableURLRequest: 0x3031b55d0> { URL: https://api-preprod.phonepe.com/apis/pg-sandboxhttps://api-preprod.phonepe.com/apis/pg-sandbox/pg/v1/pay }]
[HTTPClient] [INFO]: [["response": [:], "error": "The operation couldn’t be completed. (PhonePePayment.HTTPClientError error 0.)", "request": ["type": PhonePePayment.HTTPRequestType.POST, "bodyContentType": "application/json", "params": ["sdkContext": {
    appSupportedSchemas =     (
    );
    constraints =     (
                {
            type = "ALLOWED_RESPONSE_SCHMEMAS";
            values =             (
                "SDK_RESONSE_V2"
            );
        }
    );
    deviceOS = IOS;
    isPPAppPresent = 0;
    merchantAppId = "com.flavumhealth.Flavum";
    merchantCallBackScheme = iOSIntentIntegration;
    sdkType = native;
    supportedUriSchemas =     (
        ppe
    );
    upiApps =     (
    );
}, "request": xxx], "headers": ["X-VERIFY": ""], "queryParams": [:], "endpoint": "https://api-preprod.phonepe.com/apis/pg-sandbox/pg/v1/pay"]]]
PhonePePayment[debug]: Event name: B2B_PG_API_CALL_FAILED - data: ["transactionId": "PP_XEV1EIL4EU29XIAYJLJG", "merchantId": "", "message": "Bad Request - Api Mapping Not Found"]
failure(PhonePePayment.TransactionFailureError.networkFailure(code: "400", message: "Bad Request - Api Mapping Not Found"))
Completion:---------------------
PhonePePayment[debug]: Event name: SDK_CALLBACK_SUCCESS_TO_APP - data: ["status": "FAILURE", "merchantId": "", "transactionId": "PP_XEV1EIL4EU29XIAYJLJG", "error": "400"]

**Comment by rajanarora27** [comment]
Please contact with the integration team ([merchant-integration@phonepe.com](mailto:merchant-integration@phonepe.com)), they will help you with this
