### ISSUE TITLE
redirection Issue

### ISSUE THREAD

**Issue by vanijain3108** [PhonePe/PhonePePayment#4]
I am implementing phonepepayment gateway 
but after the payment success the phone pe success screen stuck and not going back to the code
also not coming inside the result .
it only come in result when I forcefully cut the transaction and in failed case they come 
I implement URL scheme also nothing work 
kindly help for resolving this issue 

PPPayment(environment: .sandbox, enableLogging: true, appId: phonePeAppId).startPG(transactionRequest: request, on: self, animated: true) { [self] _, result in
            print("Payment result received: \(result)") // this function never come in side result after the payment success automatically 
            
            
            below is the code which I am using 
            
            let payload = """
                {
                    "merchantId": "\(merchantId)",
                    "merchantTransactionId": "\(merchantTransactionId)",
                    "merchantUserId": "\(merchantUserId)",
                    "amount": \(amount),
                    "callbackUrl": "\(callbackUrl)",
                    "mobileNumber": "\(mobileNumber)",
                    "paymentInstrument": {
                        "type": "\(paymentInstrumentType)"
                    }
                }
                """
        let base64EncodedString = Data(payload.utf8).base64EncodedString()
        let checksum = sha256(base64EncodedString + apiEndPoint + salt) + "###" + saltIndex
        let headers: [String: String] = ["X-VERIFY": checksum]
        let request = DPSTransactionRequest(
            body: base64EncodedString,
            apiEndPoint: apiEndPoint,
            checksum: checksum,
            headers: headers,
            appSchema: "iOSIntentIntegration"
        )
       
        PPPayment(environment: .sandbox, enableLogging: true, appId: phonePeAppId).startPG(transactionRequest: request, on: self, animated: true) { [self] _, result in
            print("Payment result received: \(result)")
                switch result {
                case .success:
                    print("Transaction successful: \(result)")
                    
                case .failure(let error):
                    print("Transaction failed: \(error)")

**Comment by rajanarora27** [comment]
Please contact the integration team ([merchant-integration@phonepe.com](mailto:merchant-integration@phonepe.com)), they will help you with this.

**Comment by vanijain3108** [comment]
issue is solved 
I am added the domain in my info.plist with this key WKAppBoundDomains
so the domain mention in the value of this key is only accessible and when we want to get the response from any other domain like from phone pe response is not coming in the code bcoz we bound the domain
